### ISSUE TITLE
Catching bad app version nomenclature at time of submission

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#12]
Barry's note to an app developer:

"It seems to have surfaced a bug in the App Store that has lead to Cytoscape not starting up … everywhere in the world.

The problem is with the version naming of the CoNet app. Your previous apps were 1.0.7.beta, 1.0.6.beta, and so on. This recent version was 1.1.beta. The version name the App Store expects is <number>.<number>.<number>.<something>. 1.1.beta is illegal because “beta” isn’t a number.

This should have been caught by the App Store, but wasn’t. So, I used the App Store admin console to manually change your app version to 1.1.0.beta (with “.0” added). After this, Cytoscape starts up like it should. I wasn’t able to change the version in the manifest file, so there is still some inconsistency associated with CoNet."

**Comment by sarthak-srivastava** [comment]
I have added a regex check on submit_app/views.py to check for proper version nomenclature. The regex used works well on the local. However, the working on submitted app needs to be checked.

**Comment by sarthak-srivastava** [comment]
Closing for now...if something doesn't works properly, issue will then be re opened
