### ISSUE TITLE
 "Install" button in App Store downloads app JAR instead if license prompt is displayed

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#15]
Via Tim Hull:

I recently noticed that if you have the App Store website and Cytoscape open, clicking the "Install" button for an app with a license agreement prompt will download the JAR instead of directly installing in Cytoscape after accepting the license agreement. This works fine for apps with no license agreement displayed.

Alex: Or it should only offer "Download" button. IOW, it needs to do what it offers to do.

**Comment by AdamStuart** [comment]
On this page:
http://apps-dev.cytoscape.org/apps/agilentliteraturesearch
this license link is 404
http://blueoaksoftware.com/Agilent/ALS/license.html

**Comment by AlexanderPico** [comment]
That might be by design since it's not the production site. If this is also the case on the live site, then it's a bug. 

 - Alex

**Comment by AdamStuart** [comment]
> That might be by design since it's not the production site. If this is also the case on the live site, then it's a bug. 

It repo’ed for me in the live site, I filed a ticket.

FWIW, ENViz (shared author) license is functional.  
http://bioinfo.cs.technion.ac.il/people/zohar/ENViz/license.html <http://bioinfo.cs.technion.ac.il/people/zohar/ENViz/license.html>

How do I clear the flag that says I’ve approved licenses so I can retest with the same app?

Adam

**Comment by AlexanderPico** [comment]
Hmm. Not sure. I thought it prompted the license page every time your download the app. 

 - Alex
