### ISSUE TITLE
App Store search updates only when App Store restarts

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/appstore#16]
For now, we have installed a cron job that restarts the App Store once a day. However, we can improve service by having the search index daemon function as designed and avoiding the restart.

**Comment by AlexanderPico** [comment]
Fixed in newest instance: http://apps-test.cytoscape.org/

**Comment by bdemchak** [comment]
What fixed it??

Barry Demchak -- from my mobile phone

**Comment by AlexanderPico** [comment]
Not having docker containers.  The "fix" comes for free once we return to the simpler deployment.

**Comment by bdemchak** [comment]
Classic :)

Barry Demchak -- from my mobile phone
