### ISSUE TITLE
License link from Agilent Lit Search is 404

### ISSUE THREAD

**Issue by AdamStuart** [cytoscape/appstore#23]
On this page:
http://apps-dev.cytoscape.org/apps/agilentliteraturesearch

this license link is 404
 http://blueoaksoftware.com/Agilent/ALS/license.html

**Comment by AdamStuart** [comment]
This page is the live link:

http://apps.cytoscape.org/apps/agilentliteraturesearch

**Comment by AlexanderPico** [comment]
license link was updated by Mike Creech, one of the listed authors of the app
