### ISSUE TITLE
Manifest is not parsed properly

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#24]
In the example below, it appears the trailing whitespace after PSICQUIC is being trimmed off and the resulting app name (without a space) is then not being recognized as a valid, extant dependency.

Need to find out where in the code this whitespace trim is occurring and squash it...

Manifest-Version: 1.0
Bnd-LastModified: 1461973063033
Build-Jdk: 1.8.0_91
Built-By: thully
Bundle-Activator: org.cytoscape.internal.CyActivator
Bundle-ManifestVersion: 2
Bundle-Name: Core Apps
Bundle-SymbolicName: org.cytoscape.core-apps-meta
Bundle-Version: 3.4.0
Created-By: Apache Maven Bundle Plugin
Cytoscape-App-Dependencies: BioGRID Data Source;3.3.0,Biomart Web Servic
 e Client;3.3.0,BioPAX Reader;3.3.0.1,Command Line Implementation;3.3.0,
 CyCL;3.3.1,cyREST;3.3.2,JSON Support;3.4.0,Network Merge;3.3.1,NetworkA
 nalyzer;3.3.1,OpenCL Prefuse Layout;3.3.1,PSI-MI Reader;3.3.0,PSICQUIC 
 Web Service Client;3.3.0,SBML Reader;3.3.0,Welcome Screen;3.4.0
Import-Package: org.cytoscape.service.util;version="[3.4,4)",org.osgi.fr
 amework;version="[1.5,2)"
Tool: Bnd-1.50.0

**Comment by AdamStuart** [comment]
submit_app/mfparse.py:  rstrip is called in line 35
This code is pretty clear in the assumption that continuation lines start with a space, not end with one.

**Comment by AdamStuart** [comment]
From reading the definition of JAR format, I believe this is a user error. Space must be on the next line.

**Comment by AlexanderPico** [comment]
Here is the offending manifest as a text file so you can see the problem. I'll try to update the apps-dev site so you can reproduce it and test fixes as well...

[MANIFEST.txt](https://github.com/cytoscape/appstore/files/245957/MANIFEST.txt)

**Comment by AdamStuart** [comment]
When I tried to submit an app to the apps-dev site, it was rejected because I am not an editor.  Know where those permissions live?

Adam

**Comment by AlexanderPico** [comment]
And here is test jar that will trigger the same error on apps-dev **_(remove .zip from temporary extension)_**
[test-dependencies-1.0.jar.zip](https://github.com/cytoscape/appstore/files/246148/test-dependencies-1.0.jar.zip)

**Comment by AlexanderPico** [comment]
The fix is to comment out this line:
https://github.com/cytoscape/appstore/blob/master/submit_app/mfparse.py#L35

(having trouble updating the live code to test this)
