### ISSUE TITLE
Add link to citations

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#45]
Currently, we provide a Resources link labeled "Cite this App" based on a provided pubmed ID. Users, nonetheless, have requested a link to papers citing the app... which is the same link! 

To make this second purpose more obvious, we could add a link at the top (next to "downloads") using the same pubmed URL but labeled as "see citations" or something like that. This way users would identify the link as relevant to their intention.

**Comment by AlexanderPico** [comment]
Nice start!  A few changed needed:

- Yes, we need an "if" condition to hide the link if no citation
- Also, we should change the URL slightly, so that it goes directly to the "citedin" page for the article, following this URL pattern: https://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed_citedin&from_uid=19237447
- Also, as you can see, the text link is not very good. It's hard to distinguish it from the "downloads". First, try adding a '|' character and some space maybe? Then, change the text "citations".

**Comment by sarthak-srivastava** [comment]
If condition and "|" character for distinguishing added. Now looking into URL.

**Comment by sarthak-srivastava** [comment]
URL pattern also changed!
