### ISSUE TITLE
Add icon for apps that "support automation"

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#48]
Add another icon (i.e., internal tag) for apps that "support automation", following the same pattern used by existing annotation icons. We would also add a field in RESOURCES for a link to "Automation" documentation. Then, the icon would automatically be added whenever this field is filled in, just like how the "open source" icon works.

See icons in [this example](http://apps.cytoscape.org/apps/dynnetwork)

**Comment by AlexanderPico** [comment]
I went to the WikiPathways app page and clicked on "Edit this page" and saw the new field for "Automation Support". Great!  But when I pasted in a URL and clicked "Save". Nothing was saved and an icon was not added.

**Comment by sarthak-srivastava** [comment]
My bad...I have changed the field type to URL now.
