### ISSUE TITLE
Testing and Deployment

### ISSUE THREAD

**Issue by sarthak-srivastava** [cytoscape/appstore#51]

**Comment by AlexanderPico** [comment]
Please update these pages:
- [ ] https://github.com/cytoscape/appstore/wiki  (get rid of links to Docker related docs and update to link to the newer, active docs)
- [ ] https://github.com/cytoscape/appstore/wiki/Testing  (try to use this protocol and update if any parts are outdated or missing)
 - [ ] https://github.com/cytoscape/appstore/wiki/Troubleshooting-Search  (based on your work with haystack/whoosh, etc)
