### ISSUE TITLE
sign in leads to incorrect account names

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#53]
<img width="985" alt="screen shot 2018-07-07 at 11 10 42 am" src="https://user-images.githubusercontent.com/1418193/42412701-f2427414-81d6-11e8-842b-305ab9c83cc4.png">
When I sign in to the site now (using Google), I end up signed in with my username extended with random characters (maybe a hash of my password?). See screenshot. This account does not have the correct editing permissions.

**Comment by sarthak-srivastava** [comment]
I have placed old database (testdb) in action to deal with the problem for now. Will get to the exact cause in some time (probably after dealing with the search).
