### ISSUE TITLE
Let's Research and Assess New Versions of Python/Django/Etc

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#60]
A year has gone by, so let's research and latest versions of our software infrastructure that will all work together.

BEFORE UPGRADING, however, let's first release a feature-complete version of the site to production.  Then, we can return to the dev server and attempt the upgrade.

This would be a good proof that our site is now more "upgradeable" than it was.

**Comment by coleslaw481** [comment]
See #65.

**Comment by coleslaw481** [comment]
Closing this since the AppStore is now on Python 3.7 and Django 2.2 LTS
