### ISSUE TITLE
Upgrade django version to LTS

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#65]
Upgrade django version to 1.11 (LTS to April 2020) or 2.2 (LTS to April 2022)
https://www.djangoproject.com/download/

From Matthais (app-dev list)

**Comment by coleslaw481** [comment]
Have upgraded to `1.11.29` on `chrisdev` branch: https://github.com/cytoscape/appstore/tree/chrisdev

Working now towards `2.2` since `1.11` is no longer supported

**Comment by coleslaw481** [comment]
Upgraded to Django `2.2.13` with `2.0.0` release of AppStore
