### ISSUE TITLE
Remove Flash-based plot of stats 

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#73]
Most modern browsers don't support Flash anymore and it's typically not installed for most users. We should simply remove the plot at this time. I will open a new ticket for replacing it with a new plotter. Let's leave the CSV download button and the download count on the page. Just remove the timeline buttons and plot.

**Comment by sarthak-srivastava** [comment]
<img width="1621" alt="Screenshot 2019-08-16 at 10 49 42 AM" src="https://user-images.githubusercontent.com/21197780/63145109-b2e87080-c013-11e9-8446-1da5653916a1.png">

Currently, I have removed the plot all together. Maybe after spending some more time, we can come up with something way cooler than flash-based plots.
