### ISSUE TITLE
Download stats not working

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/appstore#75]
Clicking "Save as CSV" doesn't do anything. No change, no prompt, no error.

Tested on FF and Chrome.

**Comment by AlexanderPico** [comment]
Is there anything we can do about the filename? I'm seeing a random string and no extension. I don't really care what it's called, but it should as least end with ".csv".

**Comment by sarthak-srivastava** [comment]
I'll check out the javascript responsible

**Comment by sarthak-srivastava** [comment]
It's done!

**Comment by AlexanderPico** [comment]
Nope. On Chrome I get a file named "download" with no extension. And on FF, I don't get anything.
