### ISSUE TITLE
Comparison of minimum version of supported cytoscape fails since versions are compared as strings

### ISSUE THREAD

**Issue by coleslaw481** [cytoscape/appstore#88]
In `submit_app/mfparse.py` the method `max_of_lower_cytoscape_pkg_versions()` passes the results of `_lower_cytoscape_pkg_versions()` into the `max()` function to find the lowest version of cytoscape that will work with the app. 

The problem is the versions returned from `_lower_cytoscape_pkg_versions()` are tuples of strings and the comparisons are done alphabetically. This works fine for single digit comparisons, but fails on multiple digits.

This means when comparing say `('3','4',None,None)` with `('3','16',None,None)` the answer returned is `('3','4',None,None)` instead of the higher version. 

To correct this, the versions need to be numerically compared and either upstream code in `submit_app/processjar.py:_ver_tuple_to_str()` needs to handle the numeric values or versions need to be converted to strings before being returned.

Another thing to note is in the current implementation if any of the versions found in the manifest come back as `None` a cryptic error is returned. It would be nice to let the user know what is incorrect.

**Comment by yihangx** [comment]
Fixed. max_lower_cytoscape_pkg_versions() still returns strinngs, and works fine for multiple digits and past all test cases. Another problem is about _parse_version function in mfparse.py, this function cannot parse multiple digits version number. If the input is '3.16.0.beta' the output is ('3','6',None,'beta') , and it never return the correct version number. I also changed _parse_version function to solve this problem.
