### ISSUE TITLE
Javadocs links under release history are broken for at least one app

### ISSUE THREAD

**Issue by coleslaw481** [cytoscape/appstore#90]
For the app https://apps.cytoscape.org/apps/disgenetapp under Release History the Javadocs links next to the API lines are broken.

**Comment by jalajcodes** [comment]
@coleslaw481 
What is the expected behaviour here?

removing `_extracted` from the end of the Javadocs link seems to be downloading the jar file.

**Comment by coleslaw481** [comment]
If you click on the `Javadocs` link on an older version of DisGeNET say version `6.0.3` you'll be taken to the javadocs hosted on the appstore site. 
Example: https://apps.cytoscape.org/media/disgenetapp/releases/6.0.3/DisGeNET-app-6.0.3-javadoc.jar-extracted/

**Comment by coleslaw481** [comment]
The real issue was the jar file never got saved see issue #91 , but added some extra logic to troubleshoot issues. 
Fixed in d0ee0c4..84549af  master -> master
